name: CI
on:
  - push
  - pull_request

permissions:
  contents: write

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Updates
      run: sudo apt-get update

    - name: Dependencies
      run: sudo apt-get install python3-fontforge ttfautohint

    - name: Build
      run: |
          make -j$(nproc)
          cd build
          zip ../EBGaramond.zip *

    - name: Upload to Github Artifacts
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: EBGaramond
        path: build/

    - name: Update nightly release
      # https://stackoverflow.com/a/66206183/2278742
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && success()
      uses: pyTooling/Actions/releaser@main
      with:
        tag: nightly
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: EBGaramond.zip
